 stages:
   - check_syntax
   - apply_playbook
   - ping_test
   - setup_test
   - hostname_test

 syntax_check_job:
     stage: check_syntax
     tags:
        - runner1
     script:
        - ansible-playbook myplaybook.yaml -i hosts --syntax-check

 apply_playbook_job:
     stage: apply_playbook
     tags:
        - runner1
     script:
        - ansible-playbook myplaybook.yaml -i hosts
  
 ping_test_job:
     stage: ping_test
     tags:
          - runner1
     script:
          - ansible-playbook ping_test.yaml -i hosts

 setup_test_job:
     stage: setup_test
     tags:
          - runner1
     script:
          - ansible-playbook setup_test.yaml -i hosts

 hostname_test_job:
     stage: hostname_test
     tags:
          - runner1
     script:
          - ansible-playbook testplaybook.yaml -i hosts
          - python3 test1.py
