---
- name: AUTOMATIC SWITCH CONFIG
  hosts: Switches
  gather_facts: false
  connection: local
  vars:
          Switch1: S1
          Switch2: S2
          Switch3: S3
          Password: cisco
  tasks:
          - name: SET NAME SWITCH1
            ios_config:
                    lines:
                            - hostname {{Switch1}}
            when: inventory_hostname == "S1"
            
            
          - name: SET NAME SWITCH2
            ios_config:
                    lines:
                            - hostname {{Switch2}}
            when: inventory_hostname == "S2"
            
          - name: SET NAME SWITCH3
            ios_config:
                    lines:
                            - hostname {{Switch3}}
            when: ansible_host == "192.168.15.43"
             
          - name: SET BASIC PARAMETRS
            ios_config:
                    lines:
                            - enable secret {{Password}}
                            - service password-encryption
                            - banner motd "Authorized Access Only!"
                    save_when: modified


 
           
            
          
